from abc import ABC, abstractmethod
from pathlib import Path
from typing import AsyncGenerator, List, Optional


class EmbeddingProvider(ABC):
    """
    Abstract interface for dense embedding generation.
    Decouples vector search from specific model providers (Ollama, FastEmbed, HuggingFace).
    """

    @abstractmethod
    async def embed_texts(self, texts: List[str]) -> List[List[float]]:
        """Generates dense embeddings for a batch of text chunks."""
        pass

    @abstractmethod
    async def embed_query(self, query: str) -> List[float]:
        """Generates a dense embedding for a single user search query."""
        pass

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Returns the embedding vector dimensionality."""
        pass


class LLMProvider(ABC):
    """
    Abstract interface for text generation and reasoning.
    """

    @abstractmethod
    async def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        max_tokens: int = 1024,
        temperature: float = 0.2,
    ) -> str:
        """Generates text completion based on prompt and system instructions."""
        pass

    @abstractmethod
    async def generate_stream(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        max_tokens: int = 512,
        temperature: float = 0.1,
    ) -> AsyncGenerator[str, None]:
        """Yields incremental text tokens as they are generated by the model."""
        pass


class VisionProvider(ABC):
    """
    Abstract interface for multimodal visual reasoning on extracted images/charts.
    """

    @abstractmethod
    async def analyze_image(
        self,
        image_path: Path,
        prompt: str,
        max_tokens: int = 1024,
    ) -> str:
        """Generates visual analysis of an image given a natural language prompt."""
        pass
